name: app_de_estacionamiento
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  altfire_configurator: ^0.1.1
  booking_calendar: ^1.1.10
  firebase_admin: ^0.2.0
  flutter:
    sdk: flutter
  flutter_neumorphic: ^3.2.0
  flutterfire_cli: ^1.0.0
  go_router: ^14.1.0
  google_nav_bar: ^5.0.6
  intl: ^0.18.0
  provider: ^6.1.2
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
