// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOhU_Ce4tMhUkc4mrm7osAlITSHlUxaww',
    appId: '1:446591971525:web:5550b4fa7a18683e0e80ac',
    messagingSenderId: '446591971525',
    projectId: 'dbgarage-82054',
    authDomain: 'dbgarage-82054.firebaseapp.com',
    storageBucket: 'dbgarage-82054.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVlN5yd-uBboAg7MAjxpjfiUthlBZUN98',
    appId: '1:446591971525:android:ab2dfa5e8b73c7c20e80ac',
    messagingSenderId: '446591971525',
    projectId: 'dbgarage-82054',
    storageBucket: 'dbgarage-82054.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCORgZe2LGvt9NMgmr5o2tRtF8Y63iA44g',
    appId: '1:446591971525:ios:b86c45d20e6f86730e80ac',
    messagingSenderId: '446591971525',
    projectId: 'dbgarage-82054',
    storageBucket: 'dbgarage-82054.appspot.com',
    iosBundleId: 'com.example.appDeEstacionamiento',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCORgZe2LGvt9NMgmr5o2tRtF8Y63iA44g',
    appId: '1:446591971525:ios:b86c45d20e6f86730e80ac',
    messagingSenderId: '446591971525',
    projectId: 'dbgarage-82054',
    storageBucket: 'dbgarage-82054.appspot.com',
    iosBundleId: 'com.example.appDeEstacionamiento',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOhU_Ce4tMhUkc4mrm7osAlITSHlUxaww',
    appId: '1:446591971525:web:f57cd81b0e2c1b4e0e80ac',
    messagingSenderId: '446591971525',
    projectId: 'dbgarage-82054',
    authDomain: 'dbgarage-82054.firebaseapp.com',
    storageBucket: 'dbgarage-82054.appspot.com',
  );

}