// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfWnx6kCA6510POKkRWU0BfXAMQTJh5hY',
    appId: '1:473323408914:web:b770bf8874bf2c32ac92cb',
    messagingSenderId: '473323408914',
    projectId: 'egargedb',
    authDomain: 'egargedb.firebaseapp.com',
    storageBucket: 'egargedb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQVMNcmHezk2n_t8GR79kWem9sQaLBF_c',
    appId: '1:473323408914:android:8711c2a73239b731ac92cb',
    messagingSenderId: '473323408914',
    projectId: 'egargedb',
    storageBucket: 'egargedb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3rpT3_Pm1cxsRyIxKWBkzMEnNLqgjwtk',
    appId: '1:473323408914:ios:c939e96da345ac9dac92cb',
    messagingSenderId: '473323408914',
    projectId: 'egargedb',
    storageBucket: 'egargedb.appspot.com',
    iosBundleId: 'com.example.appDeEstacionamiento',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3rpT3_Pm1cxsRyIxKWBkzMEnNLqgjwtk',
    appId: '1:473323408914:ios:c939e96da345ac9dac92cb',
    messagingSenderId: '473323408914',
    projectId: 'egargedb',
    storageBucket: 'egargedb.appspot.com',
    iosBundleId: 'com.example.appDeEstacionamiento',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfWnx6kCA6510POKkRWU0BfXAMQTJh5hY',
    appId: '1:473323408914:web:b5bc8dbd77c5ace9ac92cb',
    messagingSenderId: '473323408914',
    projectId: 'egargedb',
    authDomain: 'egargedb.firebaseapp.com',
    storageBucket: 'egargedb.appspot.com',
  );
}
